// This file is generated by: npx supabase gen types typescript --local
// Run Task 15 (supabase start + db reset) then Task 16 to replace this placeholder.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
